version: '3.8'

x-meltano-image:
  &meltano-image
  image: el-meltano-project:dev
  build: .

services:
  meltano-dagster:
    <<: *meltano-image
    command: invoke dagster:start -h 0.0.0.0
    env_file:
      - .env
    volumes:
      - meltano_elt_logs_data:/project/.meltano/logs/elt
    expose:
      - 5000
      - 3000 # Expose port 3000
    ports:
      - 5000:5000
      - 3000:3000 # Map container port 3000 to host port 3000
    depends_on:
      - meltano-system-db
    networks:
      - meltano
    restart: unless-stopped

  meltano-system-db:
    image: postgres
    environment:
      POSTGRES_DB: postgres-meltano
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    volumes:
      - meltano_postgresql_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - meltano
    restart: unless-stopped

  metabase:
    container_name: vismetabase
    depends_on:
      - meltano-system-db
    hostname: metabase
    build: metabase/ # Dockerfile we created for metabase
    volumes:
      - ./conf/metabase:/conf
    ports:
      - 3030:3030
    networks:
      - meltano

networks:
  meltano:

volumes:
  meltano_postgresql_data:
    driver: local
  meltano_elt_logs_data:
    driver: local
